#pragma once

// For "unused parameter" warnings
#define EMU_UNUSED(x) (void)x

#define EMU_SCREEN_WIDTH 256
#define EMU_SCREEN_HEIGHT 240

#define EMU_DEFAULT_SCREEN_SCALE 2
#define EMU_DEFAULT_WINDOW_WIDTH (EMU_SCREEN_WIDTH * EMU_DEFAULT_SCREEN_SCALE)
#define EMU_DEFAULT_WINDOW_HEIGHT (EMU_SCREEN_HEIGHT * EMU_DEFAULT_SCREEN_SCALE)
